### ISSUE TITLE
Release cloudnative-pg 1.21.0

### ISSUE THREAD

**Issue by harryzcy** [cloudnative-pg/charts#151]
Can we have a release for cloudnative-pg 1.21.0?

Related #149

**Comment by harryzcy** [comment]
Thanks

**Comment by evanrich** [comment]
@NiccoloFei  QQ:  just to confirm, the 1.21.0 release is for chart 0.19.0 that just got released, right?   would it make sense to incldue al ink to the release notes in the chart readme or something too?

**Comment by NiccoloFei** [comment]
yeah, the chart v0.19.0 carries cnpg v1.21.0:

```
$ helm search repo cnpg --versions
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
...
cnpg/cloudnative-pg	0.19.0       	1.21.0     	CloudNativePG Helm Chart
```

We haven't been including release notes for the chart itself so far because we felt like it wasn't necessary as basically all of the changes are usually brought by the new version of CNPG (so you can just check out the release notes of cloudnative-pg directly). Of course that might not be the case every time.  

I see that there's another open issue https://github.com/cloudnative-pg/charts/issues/84 asking to generate GH releases also in this repository. Would that be something similar to what you're asking for? If there's lots of interest regarding that we can ask the maintainers to evaluate this proposal in the next community meeting.

**Comment by evanrich** [comment]
GH releases would be helpful for some, I'm sure.  I use Renovate to update my charts and it tracks the release of this chart, however it doesn't have release notes, so i have to compare to source, which then lead to the question since it doesn't specifically state in the source that it tracks the postgres verison (1.20->1.21 for example)
