### ISSUE TITLE
[Question] What is the relationship between the `charts` and `cloudnative-pg` versions?

### ISSUE THREAD

**Issue by xieydd** [cloudnative-pg/charts#332]
I found that the version of `charts` now is v0.21.5, and `cloudnative-pg` version is v1.23.2.

**Comment by xieydd** [comment]
@itay-grudev @gbartolini Can you take a look at this issue? Thanks a lot.

**Comment by itay-grudev** [comment]
The chart version gets increased whenever (but not only) a new version of the operator is available.

It also follows the versioning increase of the operator. A patch of the operator version will be translated to a patch increase in the chart version. A minor upgrade of the operator means a minor bump of the chart.

Updates and bug/fixes of the chart will also increase the chart version independently of the operator version, hence why the two numbers are not strictly related.

That being said you can rely on operator version you are getting by fixing the patch or minor version of the chart.

Also, since the operator versions have a very short EOL, I think it would be wiser to either check up on this regularly or leave it to auto-update. The CNPG team takes extreme caution to ensure backwards compatibility and smooth upgrades, although sometimes there may be minor side effects.

**Comment by xieydd** [comment]
> The chart version gets increased whenever (but not only) a new version of the operator is available.
> 
> It also follows the versioning increase of the operator. A patch of the operator version will be translated to a patch increase in the chart version. A minor upgrade of the operator means a minor bump of the chart.
> 
> Updates and bug/fixes of the chart will also increase the chart version independently of the operator version, hence why the two numbers are not strictly related.
> 
> That being said you can rely on operator version you are getting by fixing the patch or minor version of the chart.
> 
> Also, since the operator versions have a very short EOL, I think it would be wiser to either check up on this regularly or leave it to auto-update. The CNPG team takes extreme caution to ensure backwards compatibility and smooth upgrades, although sometimes there may be minor side effects.

Got it. Thank you for the detailed explanation.
